#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

TMP_DIR="$(mktemp -d "${TMPDIR:-/tmp}/grain-swift-bindings.XXXXXX")"
trap 'rm -rf "$TMP_DIR"' EXIT

SWIFT_ROOT="sdk/swift"
SWIFT_FFI_TARGET="$SWIFT_ROOT/Sources/GrainClientFFI"
C_FFI_TARGET="$SWIFT_ROOT/Sources/grain_client_coreFFI/include"

scripts/sdk/generate_client_bindings.sh --out-dir "$TMP_DIR" --language swift

mkdir -p "$SWIFT_FFI_TARGET" "$C_FFI_TARGET"

cp "$TMP_DIR/swift/grain_client_core.swift" "$SWIFT_FFI_TARGET/grain_client_core.swift"
cp "$TMP_DIR/swift/grain_client_coreFFI.h" "$C_FFI_TARGET/grain_client_coreFFI.h"

python3 - "$SWIFT_FFI_TARGET/grain_client_core.swift" "$C_FFI_TARGET/grain_client_coreFFI.h" <<'PY'
from pathlib import Path
import sys

for raw_path in sys.argv[1:]:
    path = Path(raw_path)
    lines = path.read_text(encoding="utf-8").splitlines()
    sanitized = []
    for line in lines:
        if line.startswith("// This file was autogenerated by") and "uniffi" in line:
            continue
        if line.startswith("// Trust "):
            continue
        if "\N{WARNING SIGN}" in line:
            continue
        sanitized.append(line.rstrip())
    while sanitized and sanitized[0] == "":
        sanitized.pop(0)
    while sanitized and sanitized[-1] == "":
        sanitized.pop()
    path.write_text("\n".join(sanitized) + "\n", encoding="utf-8")
PY

echo "swift binding sync: PASS"
