#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

TMP_DIR="$(mktemp -d "${TMPDIR:-/tmp}/grain-kotlin-bindings.XXXXXX")"
trap 'rm -rf "$TMP_DIR"' EXIT

KOTLIN_FFI_TARGET="sdk/kotlin/src/main/kotlin/uniffi/grain_client_core"

scripts/sdk/generate_client_bindings.sh --out-dir "$TMP_DIR" --language kotlin

mkdir -p "$KOTLIN_FFI_TARGET"
cp "$TMP_DIR/kotlin/uniffi/grain_client_core/grain_client_core.kt" "$KOTLIN_FFI_TARGET/grain_client_core.kt"

python3 - "$KOTLIN_FFI_TARGET/grain_client_core.kt" <<'PY'
from pathlib import Path
import sys

for raw_path in sys.argv[1:]:
    path = Path(raw_path)
    lines = path.read_text(encoding="utf-8").splitlines()
    sanitized = []
    for line in lines:
        if line.startswith("// This file was autogenerated by") and "uniffi" in line:
            continue
        if line.startswith("// Trust "):
            continue
        if "\N{WARNING SIGN}" in line:
            continue
        sanitized.append(line.rstrip())
    while sanitized and sanitized[0] == "":
        sanitized.pop(0)
    while sanitized and sanitized[-1] == "":
        sanitized.pop()
    path.write_text("\n".join(sanitized) + "\n", encoding="utf-8")
PY

echo "kotlin binding sync: PASS"
