//! SDK-level diagnostics emitted by client workflow code.

pub const SDK_ERR_TRANSPORT_VERIFY_TRUST_INVALID: &str = "SDK_ERR_TRANSPORT_VERIFY_TRUST_INVALID";
pub const SDK_ERR_SCAN_ACCEPT_TRUST_REQUIRED: &str = "SDK_ERR_SCAN_ACCEPT_TRUST_REQUIRED";
pub const SDK_ERR_STORE_ATOMIC_NESTED: &str = "SDK_ERR_STORE_ATOMIC_NESTED";
pub const SDK_ERR_STORE_CONFLICT: &str = "SDK_ERR_STORE_CONFLICT";
pub const SDK_ERR_STORE_MUTATION_OUTSIDE_ATOMIC: &str = "SDK_ERR_STORE_MUTATION_OUTSIDE_ATOMIC";
pub const SDK_ERR_STORE_SNAPSHOT_INVALID: &str = "SDK_ERR_STORE_SNAPSHOT_INVALID";
pub const SDK_ERR_STORE_SNAPSHOT_VERSION: &str = "SDK_ERR_STORE_SNAPSHOT_VERSION";
pub const SDK_ERR_TRUST_ANCHOR_NOT_FOUND: &str = "SDK_ERR_TRUST_ANCHOR_NOT_FOUND";
pub const SDK_ERR_TRUST_ANCHOR_REQUIRED: &str = "SDK_ERR_TRUST_ANCHOR_REQUIRED";
pub const SDK_ERR_CSPRNG_UNAVAILABLE: &str = "SDK_ERR_CSPRNG_UNAVAILABLE";
pub const SDK_ERR_DEVICE_EXISTS: &str = "SDK_ERR_DEVICE_EXISTS";
pub const SDK_ERR_DEVICE_UNKNOWN: &str = "SDK_ERR_DEVICE_UNKNOWN";
pub const SDK_ERR_IDENTITY_BUNDLE_INVALID: &str = "SDK_ERR_IDENTITY_BUNDLE_INVALID";
pub const SDK_ERR_IDENTITY_BUNDLE_VERSION: &str = "SDK_ERR_IDENTITY_BUNDLE_VERSION";
pub const SDK_ERR_IDENTITY_CONFLICT: &str = "SDK_ERR_IDENTITY_CONFLICT";
pub const SDK_ERR_IDENTITY_EXISTS: &str = "SDK_ERR_IDENTITY_EXISTS";
pub const SDK_ERR_IDENTITY_MISSING: &str = "SDK_ERR_IDENTITY_MISSING";
pub const SDK_ERR_PAIRING_ENVELOPE_INVALID: &str = "SDK_ERR_PAIRING_ENVELOPE_INVALID";
pub const SDK_ERR_REVOKE_ROOT_FORBIDDEN: &str = "SDK_ERR_REVOKE_ROOT_FORBIDDEN";
pub const SDK_ERR_SYNC_BUNDLE_INVALID: &str = "SDK_ERR_SYNC_BUNDLE_INVALID";
pub const SDK_ERR_UNAUTHORIZED_AK: &str = "SDK_ERR_UNAUTHORIZED_AK";
