//! SDK-level diagnostics emitted by client workflow code.

pub const SDK_ERR_TRANSPORT_VERIFY_TRUST_INVALID: &str = "SDK_ERR_TRANSPORT_VERIFY_TRUST_INVALID";
pub const SDK_ERR_SCAN_ACCEPT_TRUST_REQUIRED: &str = "SDK_ERR_SCAN_ACCEPT_TRUST_REQUIRED";
pub const SDK_ERR_STORE_ATOMIC_NESTED: &str = "SDK_ERR_STORE_ATOMIC_NESTED";
pub const SDK_ERR_STORE_CONFLICT: &str = "SDK_ERR_STORE_CONFLICT";
pub const SDK_ERR_STORE_MUTATION_OUTSIDE_ATOMIC: &str = "SDK_ERR_STORE_MUTATION_OUTSIDE_ATOMIC";
pub const SDK_ERR_TRUST_ANCHOR_NOT_FOUND: &str = "SDK_ERR_TRUST_ANCHOR_NOT_FOUND";
pub const SDK_ERR_TRUST_ANCHOR_REQUIRED: &str = "SDK_ERR_TRUST_ANCHOR_REQUIRED";
