export {
  GrainClient,
  GrainCustodyBinding,
  GrainCustodyMaterial,
  GrainCustodyPolicies,
  GrainStaticTrustProvider,
  redactGrainClientLogValue,
} from "./index.mjs";
export {
  GrainIndexedDBSnapshotPersistence,
  GrainMemorySnapshotPersistence,
  GrainSnapshotCoordinator,
  GrainSnapshotPersistenceError,
} from "./browser-storage.mjs";
export type {
  AcceptedScan,
  GrainAcceptedScan,
  GrainClientLifecycle,
  GrainClientLifecycleStatus,
  GrainCustodyBinding,
  GrainCustodyDescriptor,
  GrainCustodyMaterial,
  GrainDeviceAkInput,
  GrainDeviceResult,
  GrainDeviceStatus,
  GrainIdentityBundleInput,
  GrainIdentityResult,
  GrainIdentityStatus,
  GrainLabelInput,
  GrainPairingEnvelopeInput,
  GrainPairingResult,
  GrainPairingStatus,
  GrainScanAccept,
  GrainScanAcceptInput,
  GrainScanAcceptStatus,
  GrainScanPreview,
  GrainScanPreviewInput,
  GrainScanPreviewStatus,
  GrainTrustProvider,
  GrainTrustProviderInput,
  GrainStoreSnapshotInput,
  GrainStoreSnapshotResult,
  GrainStoreSnapshotStatus,
  GrainSyncBundleInput,
  GrainSyncResult,
  GrainSyncStatus,
} from "./index.mjs";

export function createNodeGrainClient(options: { wasmPath: string }): Promise<GrainClient>;
